# Generated by Django 4.1.9 on 2023-09-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='Book_image/'),
        ),
    ]
